{% set name = "ipysankeywidget" %}
{% set version = "0.2.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f3a1ab7481ad41c06f05e7524479109d6f5685371a85b800667253221c25fa4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - ipywidgets >=7.0.0
    - pip
    - pip
    - python
  run:
    - ipywidgets >=7.0.0
    - python

test:
  imports:
    - ipysankeywidget

about:
  home: https://github.com/ricklupton/ipysankeywidget
  license: MIT
  license_family: MIT
  license_file: 
  summary: Display Sankey diagrams in Jupyter
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
